routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

// Public Controllers
Route::get('/', 'SplashController@index');

// @TODO: Add user roles and limit this to 'admin' users
// Administrative Controllers
Route::get('home', 'HomeController@index')->name('home');

Route::resource('forms', 'FormController');
Route::resource('notification-rules', 'NotificationRuleController');

Route::resource('entries', 'EntryController', [
    'except' => ['create']
]);

resources/views/home.blade.php
@extends('layouts.app')

@section('content')

@component('components.panel')
    @slot('title')
    Forms
    @endslot

    <div class="clearfix">
        <a role="button" class="btn btn-primary pull-right" href="{{ route('forms.create') }}">Add New</a>
    </div>

    @if(isset($forms) && count($forms) > 0)
        @include('tables.forms')
    @else
        <p>No forms yet! Why not <a href="{{ route('forms.create') }}">Create a form?</a>
    @endif
@endcomponent

@component('components.panel')
    @slot('title')
    Recent Entries
    @endslot

    @if(isset($entries) && count($entries) > 0)
        @include('tables.entries')
    @else
        <p>No form entries yet!
        @if(isset($forms) && count($forms) <= 0)
            Why not <a href="{{ route('forms.create') }}">Create a form?</a>
        @elseif(isset($forms) && count($forms) > 0)
            It won't be long until someone fills out your forms! Check back later.
        @endif
    @endif
@endcomponent

@endsection

resources/views/splash.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Raleway', sans-serif;
                font-weight: 100;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 12px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            @if (Route::has('login'))
                <div class="top-right links">
                    @if (Auth::check())
                        <a href="{{ url('/home') }}">Home</a>
                    @else
                        <a href="{{ url('/login') }}">Login</a>
                    @endif
                </div>
            @endif

            <div class="content">
                <div class="title m-b-md">
                    {{ config('app.name') }}
                </div>
                <h2>Internal Application to Handle Form Submissions</h2>
            </div>
        </div>
    </body>
</html>