routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

// Public Controllers
Route::get('/', 'SplashController@index');

// @TODO: Add user roles and limit this to 'admin' users
// Administrative Controllers
Route::get('home', 'HomeController@index')->name('home');

Route::resource('forms', 'FormController');
Route::resource('notification-rules', 'NotificationRuleController');

Route::resource('entries', 'EntryController', [
    'except' => ['create']
]);

app/Http/Controllers/FormController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Form;

class FormController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('forms.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'url' => 'required|url',
        ]);

        $form = Form::create([
            'name' => $request->input('name'),
            'url' => $request->input('url'),
            'token' => md5($request->input('name') . $request->input('url') . str_random(10))
        ]);
        return redirect()->route('forms.show', [$form]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Form  $form
     * @return \Illuminate\Http\Response
     */
    public function show(Form $form)
    {
        return view('forms.show', [
            'form' => $form,
            'entries' => $form->entries,
            'recipients' => $form->emailNotificationRecipients()
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Form  $form
     * @return \Illuminate\Http\Response
     */
    public function edit(Form $form)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Form  $form
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Form $form)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Form  $form
     * @return \Illuminate\Http\Response
     */
    public function destroy(Form $form)
    {
        //
    }
}

resources/views/forms/create.blade.php
@extends('layouts.app')

@section('content')

@component('components.panel')
    @slot('title')
        Create a Form
    @endslot


    <div class="clearfix">
        <a role="button" class="btn btn-danger pull-right" href="{{ route('home') }}">Back</a>
    </div>


    <form action="{{ route('forms.store') }}" method="POST">
        {{ csrf_field() }}
        {{ method_field('POST') }}

        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
            <label for="name">Form Name</label>
            <input class="form-control" type="text" placeholder="Name" name="name" value="{{ old('name') }}" required>
            @if ($errors->has('url'))
                <span class="help-block">
                    <strong>{{ $errors->first('name') }}</strong>
                </span>
            @endif
        </div>
        <div class="form-group{{ $errors->has('url') ? ' has-error' : '' }}">
            <label for="url">Form URL/Permalink</label>
            <input class="form-control" type="text" placeholder="Url" name="url" value="{{ old('url') }}" required>
            <span class="help-block">This should be the base url of your site, for example <code>http://mysite.com</code>.</span>
            @if ($errors->has('url'))
                <span class="help-block">
                    <strong>{{ $errors->first('url') }}</strong>
                </span>
            @endif
        </div>
        <button class="btn btn-success" type="submit">Save Form</button>
    </form>
@endcomponent

@endsection

resources/views/forms/show.blade.php
@extends('layouts.app')

@section('content')

@component('components.panel')
    @slot('title')
        View Form: {{ $form->name }}
    @endslot

    <div class="pull-right">
        <a role="button" class="btn btn-primary" href="{{ route('forms.edit', ['id' => $form->id]) }}">Edit Form</a>
        <a role="button" class="btn btn-danger" href="{{ route('home') }}">Back</a>
    </div>

    <h2 class="h5">URL</h2>
    <p>Be sure your form is served from:<br><code>{{ $form->url }}</code></p>

    <hr>
    <h2 class="h5">Token Field (Required)</h2>
    <p>Be sure your form includes the following field:<br><code>{{ '<input name="token" value="' . $form->token . '">' }}</code></p>

    <hr>
    <h2 class="h5">Notifications</h2>
    <p>Each email address listed here wil receive an email every time a user submits your form. Please provide a comma seperated list of recipients.</p>

    <form action="{{ route('notification-rules.store') }}" method="POST">
        {{ csrf_field() }}
        {{ method_field('POST') }}

        <div class="form-group{{ $errors->has('recipients') ? ' has-error' : '' }}">
            <label for="name">Recipients</label>
            <input class="form-control" type="text" placeholder="email@website.com, fake@yourwebsite.com" name="recipients"
            @if($recipients && count($recipients > 0))
                    value="{{ implode(', ', $recipients) }}"
            @endif required>
            @if ($errors->has('recipients'))
                <span class="help-block">
                    <strong>{{ $errors->first('recipients') }}</strong>
                </span>
            @endif
        </div>

        <input type="hidden" name="form_id" value="{{ $form->id }}" required>
        <button class="btn btn-success" type="submit">Save Recipients</button>
    </form>
@endcomponent

@component('components.panel')
    @slot('title')
        Entries
    @endslot

    @if(isset($entries) && count($entries) > 0)
        @include('tables.entries')
    @else
        <p>It won't be long until someone fills out your form! Check back later.</p>
    @endif
@endcomponent

@endsection